### ISSUE TITLE
support for image_url in SlackAttachment

### ISSUE THREAD

**Issue by munwaikong** [ashwanthkumar/slack-java-webhook#1]
Hey, great work with the API.

Can you please add support for image_url in the SlackAttachment.java class?

Thanks,

Mun

**Comment by ashwanthkumar** [comment]
Thanks for reporting. I'll do it this week when I have time and let you know.

**Comment by ashwanthkumar** [comment]
@munwaikong This should now be available as `SlackAttachment#imageUrl`. Check out the 0.0.4 version.
